image: rust:latest

check:
  stage: test
  before_script:
    - apt -y update
    - apt install -y ffmpeg
    - rustup component add clippy rustfmt
  script:
    - RUST_LOG=debug cargo test
    - cargo clippy -- -D warnings
    - cargo fmt -- --check
